/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PipelineDemoRouteImport } from './routes/pipeline-demo'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AgentsDemoRouteImport } from './routes/agents-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIdRouteImport } from './routes/stories/$id'
import { Route as StoriesIdAgentsRouteImport } from './routes/stories/$id.agents'

const PipelineDemoRoute = PipelineDemoRouteImport.update({
  id: '/pipeline-demo',
  path: '/pipeline-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDemoRoute = AgentsDemoRouteImport.update({
  id: '/agents-demo',
  path: '/agents-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdAgentsRoute = StoriesIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => StoriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents-demo': typeof AgentsDemoRoute
  '/demo': typeof DemoRoute
  '/pipeline-demo': typeof PipelineDemoRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/agents': typeof StoriesIdAgentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents-demo': typeof AgentsDemoRoute
  '/demo': typeof DemoRoute
  '/pipeline-demo': typeof PipelineDemoRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/agents': typeof StoriesIdAgentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents-demo': typeof AgentsDemoRoute
  '/demo': typeof DemoRoute
  '/pipeline-demo': typeof PipelineDemoRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/agents': typeof StoriesIdAgentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents-demo'
    | '/demo'
    | '/pipeline-demo'
    | '/stories/$id'
    | '/stories/$id/agents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents-demo'
    | '/demo'
    | '/pipeline-demo'
    | '/stories/$id'
    | '/stories/$id/agents'
  id:
    | '__root__'
    | '/'
    | '/agents-demo'
    | '/demo'
    | '/pipeline-demo'
    | '/stories/$id'
    | '/stories/$id/agents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsDemoRoute: typeof AgentsDemoRoute
  DemoRoute: typeof DemoRoute
  PipelineDemoRoute: typeof PipelineDemoRoute
  StoriesIdRoute: typeof StoriesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pipeline-demo': {
      id: '/pipeline-demo'
      path: '/pipeline-demo'
      fullPath: '/pipeline-demo'
      preLoaderRoute: typeof PipelineDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents-demo': {
      id: '/agents-demo'
      path: '/agents-demo'
      fullPath: '/agents-demo'
      preLoaderRoute: typeof AgentsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id/agents': {
      id: '/stories/$id/agents'
      path: '/agents'
      fullPath: '/stories/$id/agents'
      preLoaderRoute: typeof StoriesIdAgentsRouteImport
      parentRoute: typeof StoriesIdRoute
    }
  }
}

interface StoriesIdRouteChildren {
  StoriesIdAgentsRoute: typeof StoriesIdAgentsRoute
}

const StoriesIdRouteChildren: StoriesIdRouteChildren = {
  StoriesIdAgentsRoute: StoriesIdAgentsRoute,
}

const StoriesIdRouteWithChildren = StoriesIdRoute._addFileChildren(
  StoriesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsDemoRoute: AgentsDemoRoute,
  DemoRoute: DemoRoute,
  PipelineDemoRoute: PipelineDemoRoute,
  StoriesIdRoute: StoriesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
