/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIdRouteImport } from './routes/stories/$id'
import { Route as StoriesIdAgentsRouteImport } from './routes/stories/$id.agents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdAgentsRoute = StoriesIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => StoriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/agents': typeof StoriesIdAgentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/agents': typeof StoriesIdAgentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stories/$id': typeof StoriesIdRouteWithChildren
  '/stories/$id/agents': typeof StoriesIdAgentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stories/$id' | '/stories/$id/agents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stories/$id' | '/stories/$id/agents'
  id: '__root__' | '/' | '/stories/$id' | '/stories/$id/agents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesIdRoute: typeof StoriesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id/agents': {
      id: '/stories/$id/agents'
      path: '/agents'
      fullPath: '/stories/$id/agents'
      preLoaderRoute: typeof StoriesIdAgentsRouteImport
      parentRoute: typeof StoriesIdRoute
    }
  }
}

interface StoriesIdRouteChildren {
  StoriesIdAgentsRoute: typeof StoriesIdAgentsRoute
}

const StoriesIdRouteChildren: StoriesIdRouteChildren = {
  StoriesIdAgentsRoute: StoriesIdAgentsRoute,
}

const StoriesIdRouteWithChildren = StoriesIdRoute._addFileChildren(
  StoriesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesIdRoute: StoriesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
