#!/usr/bin/env python3
"""
SandSync Demo Video Builder
Assembles a 2-3 minute demo video showing the end-to-end story generation pipeline
"""

import os
import subprocess
import tempfile
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

# Configuration
WORKSPACE = Path(os.path.expanduser("~/.openclaw/workspace"))
CONTENT_DIR = WORKSPACE / "content"
SANDSYNC_DIR = Path(os.path.expanduser("~/projects/sandsync"))
OUTPUT_FILE = SANDSYNC_DIR / "DEMO_VIDEO.mp4"
TEMP_DIR = Path(tempfile.gettempdir()) / "sandsync-demo"
TEMP_DIR.mkdir(exist_ok=True)

# Video specs
VIDEO_WIDTH = 1920
VIDEO_HEIGHT = 1080
FPS = 30
DURATION_PER_FRAME = 3  # seconds per image
TARGET_DURATION = 150  # Target 2.5 minutes in seconds

def create_title_card(text, subtitle="", output_path="title.png"):
    """Create a title card with text overlay"""
    img = Image.new('RGB', (VIDEO_WIDTH, VIDEO_HEIGHT), color=(15, 23, 42))  # Dark blue
    draw = ImageDraw.Draw(img)
    
    try:
        title_font = ImageFont.truetype("/System/Library/Fonts/SF-Pro-Display-Semibold.otf", 120)
        subtitle_font = ImageFont.truetype("/System/Library/Fonts/SF-Pro-Text-Regular.otf", 48)
    except:
        title_font = ImageFont.load_default()
        subtitle_font = ImageFont.load_default()
    
    # Draw title
    title_bbox = draw.textbbox((0, 0), text, font=title_font)
    title_width = title_bbox[2] - title_bbox[0]
    title_x = (VIDEO_WIDTH - title_width) // 2
    title_y = (VIDEO_HEIGHT - 200) // 2
    
    draw.text((title_x, title_y), text, fill=(255, 255, 255), font=title_font)
    
    # Draw subtitle if provided
    if subtitle:
        sub_bbox = draw.textbbox((0, 0), subtitle, font=subtitle_font)
        sub_width = sub_bbox[2] - sub_bbox[0]
        sub_x = (VIDEO_WIDTH - sub_width) // 2
        sub_y = title_y + 150
        draw.text((sub_x, sub_y), subtitle, fill=(156, 163, 175), font=subtitle_font)
    
    img.save(output_path)
    return str(output_path)

def scale_image_to_fit(input_path, output_path, width=VIDEO_WIDTH, height=VIDEO_HEIGHT):
    """Scale image to fit video dimensions, adding black bars if needed"""
    img = Image.open(input_path)
    
    # Calculate aspect ratios
    img_ratio = img.width / img.height
    target_ratio = width / height
    
    if img_ratio > target_ratio:
        # Image is wider, fit to width
        new_width = width
        new_height = int(width / img_ratio)
    else:
        # Image is taller, fit to height
        new_height = height
        new_width = int(height * img_ratio)
    
    # Resize
    img = img.resize((new_width, new_height), Image.Resampling.LANCZOS)
    
    # Create canvas with black background
    canvas = Image.new('RGB', (width, height), (0, 0, 0))
    paste_x = (width - new_width) // 2
    paste_y = (height - new_height) // 2
    canvas.paste(img, (paste_x, paste_y))
    
    canvas.save(output_path)
    return str(output_path)

def build_scene_list():
    """Build list of scenes for the demo video"""
    scenes = []
    
    # 1. OPENING TITLE
    title_card = create_title_card(
        "SandSync",
        "AI-Powered Caribbean Storytelling",
        str(TEMP_DIR / "01_title.png")
    )
    scenes.append((title_card, "title", 8))
    
    # 2. INTRO - What is SandSync?
    title_card = create_title_card(
        "An end-to-end",
        "AI storytelling pipeline",
        str(TEMP_DIR / "02_intro.png")
    )
    scenes.append((title_card, "intro", 6))
    
    # 3. STORY REQUEST - User Interface
    title_card = create_title_card(
        "Step 1: Story Request",
        "User selects theme & genre",
        str(TEMP_DIR / "03_step1.png")
    )
    scenes.append((title_card, "step", 4))
    scenes.append((CONTENT_DIR / "redesign_creator.png", "request", 8))
    
    # 4. ANANSI STORYTELLER AGENT
    title_card = create_title_card(
        "Step 2: Anansi Storyteller",
        "Agent orchestration & narrative generation",
        str(TEMP_DIR / "04_step2.png")
    )
    scenes.append((title_card, "step", 4))
    
    if (CONTENT_DIR / "pipeline_full_check.png").exists():
        scenes.append((CONTENT_DIR / "pipeline_full_check.png", "pipeline", 8))
    
    # 5. VISUAL GENERATION - fal.ai
    title_card = create_title_card(
        "Step 3: Illustrations",
        "Generated by fal.ai FLUX",
        str(TEMP_DIR / "05_step3.png")
    )
    scenes.append((title_card, "step", 4))
    
    # Add generated image samples
    if (CONTENT_DIR / "images/flux_result.png").exists():
        scenes.append((CONTENT_DIR / "images/flux_result.png", "image", 6))
    
    if (CONTENT_DIR / "images/dalle3_standard_20260226_164131.png").exists():
        scenes.append((CONTENT_DIR / "images/dalle3_standard_20260226_164131.png", "image", 6))
    
    # 6. QUALITY REFINEMENT - Ogma
    title_card = create_title_card(
        "Step 4: Ogma Guardian",
        "Language review & cultural authenticity",
        str(TEMP_DIR / "06_step4.png")
    )
    scenes.append((title_card, "step", 4))
    
    if (CONTENT_DIR / "verify_sophie.png").exists():
        scenes.append((CONTENT_DIR / "verify_sophie.png", "verify", 8))
    
    # 7. AUDIO NARRATION
    title_card = create_title_card(
        "Step 5: Voice Narration",
        "ElevenLabs AI voice generation",
        str(TEMP_DIR / "07_audio.png")
    )
    scenes.append((title_card, "step", 4))
    
    # 8. PUBLISHED STORY
    title_card = create_title_card(
        "Step 6: Story Published",
        "Ready for readers",
        str(TEMP_DIR / "08_published.png")
    )
    scenes.append((title_card, "step", 4))
    scenes.append((CONTENT_DIR / "redesign_reader.png", "result", 8))
    
    # 9. LIBRARY VIEW
    if (CONTENT_DIR / "redesign_library.png").exists():
        title_card = create_title_card(
            "Story Library",
            "All your Caribbean tales",
            str(TEMP_DIR / "09_library.png")
        )
        scenes.append((title_card, "step", 4))
        scenes.append((CONTENT_DIR / "redesign_library.png", "library", 8))
    
    # 10. OFFLINE SYNC
    title_card = create_title_card(
        "Powered by PowerSync",
        "Offline-first synchronization",
        str(TEMP_DIR / "10_sync.png")
    )
    scenes.append((title_card, "feature", 6))
    
    # 11. TECHNOLOGY STACK
    title_card = create_title_card(
        "Tech Stack",
        "Supabase · Mastra · Claude AI · ElevenLabs",
        str(TEMP_DIR / "11_tech.png")
    )
    scenes.append((title_card, "tech", 6))
    
    # 12. CLOSING
    title_card = create_title_card(
        "SandSync",
        "Caribbean Folklore, Reimagined",
        str(TEMP_DIR / "12_closing.png")
    )
    scenes.append((title_card, "closing", 8))
    
    return scenes

def prepare_frames(scenes):
    """Prepare all frames for video composition"""
    prepared_frames = []
    
    for i, (source, scene_type, duration) in enumerate(scenes):
        source_path = Path(source)
        if not source_path.exists():
            print(f"⚠️  Skipping missing: {source_path}")
            continue
        
        output_path = TEMP_DIR / f"frame_{i:02d}.png"
        
        # Scale to video dimensions
        scale_image_to_fit(str(source_path), str(output_path))
        
        # Calculate frame count for this scene
        frame_count = int(duration * FPS)
        
        for _ in range(frame_count):
            prepared_frames.append(str(output_path))
    
    return prepared_frames

def create_video_from_frames(frames, output_file):
    """Create MP4 video from frame sequence using ffmpeg"""
    if not frames:
        print("❌ No frames to process!")
        return False
    
    # Write frame list to concat file
    concat_file = TEMP_DIR / "concat.txt"
    with open(concat_file, 'w') as f:
        for frame in frames:
            # Each frame gets displayed for 1 frame duration
            f.write(f"file '{frame}'\nduration {1/FPS}\n")
    
    # Use ffmpeg concat demuxer
    cmd = [
        "/Users/loki/.local/bin/ffmpeg",
        "-f", "concat",
        "-safe", "0",
        "-i", str(concat_file),
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-crf", "20",  # Quality (lower = better, 0-51)
        "-vf", f"fps={FPS}",
        "-preset", "slow",  # Slower = better compression
        "-y",  # Overwrite output
        str(output_file)
    ]
    
    print(f"🎬 Encoding video: {output_file}")
    print(f"📊 Total frames: {len(frames)}")
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"❌ FFmpeg error: {result.stderr}")
        return False
    
    return True

def main():
    print("🎬 SandSync Demo Video Builder")
    print(f"📁 Workspace: {WORKSPACE}")
    print(f"📁 Output: {OUTPUT_FILE}")
    
    # Build scene list
    print("\n📋 Building scene list...")
    scenes = build_scene_list()
    print(f"✅ {len(scenes)} scenes planned")
    
    # Prepare frames
    print("\n📸 Preparing frames...")
    frames = prepare_frames(scenes)
    print(f"✅ {len(frames)} total frames prepared")
    
    # Calculate video duration
    duration_seconds = len(frames) / FPS
    print(f"⏱️  Estimated duration: {duration_seconds:.1f} seconds ({duration_seconds/60:.2f} minutes)")
    
    # Create video
    print("\n🎥 Creating video...")
    if create_video_from_frames(frames, OUTPUT_FILE):
        print(f"\n✅ Demo video created: {OUTPUT_FILE}")
        
        # Show file info
        if OUTPUT_FILE.exists():
            size_mb = OUTPUT_FILE.stat().st_size / (1024*1024)
            print(f"📦 File size: {size_mb:.1f} MB")
            return True
    else:
        print("❌ Video creation failed")
        return False
    
    return False

if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
