-- SandSync Initial Schema
-- PowerSync AI Hackathon 2026
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Stories table
create table stories (
  id uuid primary key default uuid_generate_v4(),
  user_id text not null,
  title text,
  genre text,
  status text default 'queued', -- queued | generating | complete | failed
  created_at timestamptz default now()
);

-- Story chapters
create table story_chapters (
  id uuid primary key default uuid_generate_v4(),
  story_id uuid references stories(id) on delete cascade,
  chapter_number int not null,
  content text,          -- written by Anansi
  reviewed_content text, -- polished by Ogma
  audio_url text,        -- generated by Devi (ElevenLabs)
  agent_trace jsonb default '{}',  -- which agent wrote this, latency, model
  created_at timestamptz default now()
);

-- Agent events
create table agent_events (
  id uuid primary key default uuid_generate_v4(),
  story_id uuid references stories(id) on delete cascade,
  agent text not null,       -- papa_bois | anansi | ogma | devi
  event_type text not null,  -- started | completed | failed
  payload jsonb default '{}',
  created_at timestamptz default now()
);

-- Row Level Security
alter table stories enable row level security;
alter table story_chapters enable row level security;
alter table agent_events enable row level security;

-- RLS policies (user can only see their own stories)
create policy "Users see own stories" on stories
  for all using (auth.uid()::text = user_id);

create policy "Users see own chapters" on story_chapters
  for all using (
    story_id in (select id from stories where user_id = auth.uid()::text)
  );

create policy "Users see own events" on agent_events
  for all using (
    story_id in (select id from stories where user_id = auth.uid()::text)
  );

-- Indexes for PowerSync performance
create index on story_chapters(story_id, chapter_number);
create index on agent_events(story_id, created_at);
